const demoProfiles=[
 {id:'demo-amina',display_name:'Amina',birthdate:'2002-04-15',city:'West Loop · 3 miles',occupation:'Creative strategist',relationship_intent:'Long-term relationship',bio:'Live music, tiny restaurants, and taking the scenic route on purpose.',interests:['Live music','Food spots','Photography'],prompts:[{q:'A small thing that tells me a lot about someone',a:'How they treat people when there is absolutely nothing to gain.'}],verification_status:'demo',profile_status:'active',demo:true},
 {id:'demo-jordan',display_name:'Jordan',birthdate:'2000-08-21',city:'Pilsen · 4 miles',occupation:'Product designer',relationship_intent:'Relationship, open to short',bio:'Museum dates, old R&B, pickup basketball, and finding the best tacos in the city.',interests:['Design','Basketball','R&B'],prompts:[{q:'The quickest way to win me over',a:'Make a plan instead of saying “whatever you want.”'}],verification_status:'demo',profile_status:'active',demo:true},
 {id:'demo-maya',display_name:'Maya',birthdate:'2001-12-03',city:'Hyde Park · 7 miles',occupation:'Grad student',relationship_intent:'Long-term relationship',bio:'Books, lakefront walks, stand-up comedy and very serious brunch opinions.',interests:['Books','Comedy','Brunch'],prompts:[{q:'My simple pleasure',a:'Walking somewhere with no reason to rush.'}],verification_status:'demo',profile_status:'active',demo:true}
];
async function getProfiles(){if(!backendReady)return demoProfiles;let rows=await sb('/rest/v1/profiles?profile_status=eq.active&select=*&order=created_at.desc&limit=50');rows=rows.filter(x=>x.id!==state.user.id);return rows}
async function countLikesToday(){if(!backendReady)return localLikes().length;const since=new Date();since.setUTCHours(0,0,0,0);const rows=await sb('/rest/v1/likes?liker_id=eq.'+state.user.id+'&created_at=gte.'+encodeURIComponent(since.toISOString())+'&select=id');return rows.length}
async function loadDiscover(){if(!state.profile){await loadOwnProfile();if(!state.profile)return show('onboarding')}try{const used=await countLikesToday();$('#likesLeft').textContent=Math.max(0,10-used)+' likes left';state.profiles=await getProfiles();renderDiscover()}catch(e){$('#discoverHost').innerHTML=`<div class="card empty"><div class="big">⚠️</div><div class="vibe">Couldn’t load people</div><div class="mini">${esc(e.message)}</div></div>`}}
async function renderDiscover(){const host=$('#discoverHost'),usedIds=new Set((!backendReady?localLikes():[]).map(x=>x.liked_id));const p=state.profiles.find(x=>!usedIds.has(x.id));if(!p){host.innerHTML=`<div class="card empty"><div class="big">✨</div><div class="vibe">No new sparks right now</div><div class="muted">That is not a dead end. Try a Vibe Flip while your next set fills.</div><div class="card flat"><strong id="vibePrompt">Text a friend one thing you actually want in your next relationship.</strong></div><button class="btn primary" id="vibeFlip">Flip the vibe</button></div>`;$('#vibeFlip').onclick=()=>{$('#vibePrompt').textContent=['Pick a first date you would genuinely be excited to go on.','Write one green flag you refuse to compromise on.','Put on the song that makes you feel most like yourself.','Call the friend who gives you the best dating advice.'][Math.floor(Math.random()*4)]};return}
state.currentProfile=p;const img=await mediaUrl(p.avatar_path);host.innerHTML=`<div class="card profileCard"><div class="photo">${img?`<img src="${esc(img)}" alt="${esc(p.display_name)}">`:`<div class="initials">${initials(p.display_name)}</div>`}<div class="photoOverlay"><div class="row between"><div><div class="name">${esc(p.display_name)}, ${age(p.birthdate)}</div><div class="meta">${esc(p.occupation||'')} · ${esc(p.city||'')}</div></div>${p.demo?'<span class="pill warn">Demo profile</span>':p.verification_status==='verified'?'<span class="pill good">Verified</span>':p.presence_submitted_at?'<span class="pill good">Presence submitted</span>':'<span class="pill warn">Unverified</span>'}</div><div class="chips">${(p.interests||[]).slice(0,5).map(i=>`<span class="pill">${esc(i)}</span>`).join('')}</div></div></div><div style="padding:16px"><div class="eyebrow">${esc(p.relationship_intent||'')}</div><p>${esc(p.bio||'')}</p>${(p.prompts||[]).slice(0,2).map(q=>`<div class="card flat"><div class="mini">${esc(q.q)}</div><strong>${esc(q.a)}</strong></div>`).join('')}<div class="row"><button class="btn ghost" id="reportProfile">Report</button><button class="btn ghost" id="blockProfile">Block</button></div></div><div class="actions"><button class="pass" id="passBtn">Pass</button><button class="like" id="likeBtn">Like ${esc(p.display_name)}</button></div></div>`;$('#passBtn').onclick=()=>{state.profiles=state.profiles.filter(x=>x.id!==p.id);renderDiscover()};$('#likeBtn').onclick=()=>likeProfile(p);$('#reportProfile').onclick=()=>{state.currentProfile=p;openModal('reportModal')};$('#blockProfile').onclick=()=>blockProfile(p)}
async function likeProfile(p){if(p.demo&&!backendReady){const a=localLikes();if(a.length>=10)return toast('You used today’s 10 free likes.');a.push({liked_id:p.id,created_at:new Date().toISOString()});localStorage.setItem(likesKey(),JSON.stringify(a));toast('Like saved in preview');state.profiles=state.profiles.filter(x=>x.id!==p.id);loadDiscover();return}try{const result=await sb('/rest/v1/rpc/like_profile',{method:'POST',body:{target_user:p.id}});toast('Liked '+p.display_name);if(result?.matched&&result?.match_id){const ms=await fetchMatches();const m=ms.find(x=>x.id===result.match_id);if(m){state.currentMatch=m;$('#matchText').textContent=`You and ${p.display_name} both liked each other.`;openModal('matchModal')}}state.profiles=state.profiles.filter(x=>x.id!==p.id);loadDiscover()}catch(e){toast(e.message)}}
async function blockProfile(p){if(p.demo&&!backendReady){state.profiles=state.profiles.filter(x=>x.id!==p.id);toast('Demo profile hidden');return renderDiscover()}try{await sb('/rest/v1/blocks',{method:'POST',headers:{Prefer:'return=minimal'},body:{blocker_id:state.user.id,blocked_id:p.id}});state.profiles=state.profiles.filter(x=>x.id!==p.id);toast('Profile blocked');renderDiscover()}catch(e){toast(e.message)}}
