async function fetchMatches(){if(!backendReady)return JSON.parse(localStorage.getItem('veramor_matches')||'[]');const a=await sb('/rest/v1/matches?or=(user_a.eq.'+state.user.id+',user_b.eq.'+state.user.id+')&status=eq.active&select=*&order=created_at.desc');return a||[]}
async function loadMatches(){try{state.matches=await fetchMatches();$('#matchCount').textContent=state.matches.length;const host=$('#matchList');if(!state.matches.length){host.innerHTML='<div class="empty"><div class="big">♡</div><div class="vibe">Your matches will show up here</div><div class="mini">Mutual likes create a match. Chat stays locked until both people complete the Chemistry Check.</div></div>';return}host.innerHTML='';for(const m of state.matches){const otherId=m.user_a===state.user.id?m.user_b:m.user_a;let p;if(backendReady){const rows=await sb('/rest/v1/profiles?id=eq.'+otherId+'&select=*');p=rows[0]}else p=demoProfiles.find(x=>x.id===otherId)||{id:otherId,display_name:'Match'};if(!p)continue;const av=await mediaUrl(p.avatar_path);const div=document.createElement('div');div.className='matchItem';div.innerHTML=`<div class="avatar">${av?`<img src="${esc(av)}">`:initials(p.display_name)}</div><div style="flex:1"><strong>${esc(p.display_name)}</strong><div class="mini">${m.chemistry_complete_a&&m.chemistry_complete_b?'Chat unlocked':'Chemistry Check pending'}</div></div><button class="iconBtn">›</button>`;div.onclick=()=>openChat(m,p);host.appendChild(div)}}catch(e){toast(e.message)}}
function chemistryOwnComplete(m){return m.user_a===state.user.id?m.chemistry_complete_a:m.chemistry_complete_b}
async function openChat(m,p){state.currentMatch={...m,other:p};$('#chatName').textContent=p.display_name;openModal('chatModal');await renderChemistry();await loadMessages();clearInterval(state.poll);if(backendReady)state.poll=setInterval(()=>{if($('#chatModal').classList.contains('show'))loadMessages(false)},4000)}
async function renderChemistry(){let m=state.currentMatch;if(backendReady){const rows=await sb('/rest/v1/matches?id=eq.'+m.id+'&select=*');if(rows[0]){m={...rows[0],other:m.other};state.currentMatch=m}}const both=m.chemistry_complete_a&&m.chemistry_complete_b,own=chemistryOwnComplete(m);$('#chatStatus').textContent=both?'Chemistry Check complete · messaging open':'Messaging locked until both finish';$('#chatInput').disabled=!both;$('#sendMessage').disabled=!both;$('#chemistryBox').innerHTML=both?'<span class="pill good">✓ Chemistry Check complete</span>':`<strong>15-second Chemistry Check</strong><div class="mini">Both people answer one quick prompt before messaging unlocks.</div><div class="card flat">What is something you genuinely want to make time for this month?</div>${own?'<span class="pill good">You finished · waiting on them</span>':'<button class="btn primary" id="chemBtn">Start 15 sec check</button>'}`;if(!own&&!both)$('#chemBtn').onclick=async()=>{const b=$('#chemBtn');b.disabled=true;let n=15;b.textContent=`Answer out loud… ${n}`;const timer=setInterval(async()=>{n--;b.textContent=`Answer out loud… ${n}`;if(n<=0){clearInterval(timer);try{if(!backendReady){const mm=state.currentMatch;if(mm.user_a===state.user.id)mm.chemistry_complete_a=true;else mm.chemistry_complete_b=true}else{await sb('/rest/v1/rpc/set_chemistry_complete',{method:'POST',body:{match_uuid:state.currentMatch.id}})}toast('Your Chemistry Check is complete');await renderChemistry()}catch(e){toast(e.message)}}},1000)}}
async function loadMessages(scroll=true){const host=$('#chatMessages');if(!backendReady){host.innerHTML='<div class="empty"><div class="mini">Preview chat has no real recipient.</div></div>';return}try{const rows=await sb('/rest/v1/messages?match_id=eq.'+state.currentMatch.id+'&select=*&order=created_at.asc');host.innerHTML=rows.map(x=>`<div class="bubble ${x.sender_id===state.user.id?'me':'them'}">${esc(x.body)}</div>`).join('');if(scroll)host.scrollTop=host.scrollHeight}catch(e){toast(e.message)}}
$('#sendMessage').onclick=async()=>{const body=$('#chatInput').value.trim();if(!body)return;if(bannedText(body))return toast('Links and solicitation are not allowed in chat.');try{await sb('/rest/v1/messages',{method:'POST',headers:{Prefer:'return=minimal'},body:{match_id:state.currentMatch.id,sender_id:state.user.id,body}});$('#chatInput').value='';loadMessages()}catch(e){toast(e.message)}};
$('#unmatchBtn').onclick=async()=>{if(!confirm('Unmatch? This closes the conversation.'))return;try{if(backendReady)await sb('/rest/v1/rpc/unmatch',{method:'POST',body:{match_uuid:state.currentMatch.id}});closeModal('chatModal');toast('Unmatched');loadMatches()}catch(e){toast(e.message)}};
$('#chatReportBtn').onclick=()=>{state.currentProfile=state.currentMatch.other;openModal('reportModal')};
$('#matchContinue').onclick=()=>{closeModal('matchModal');if(state.currentMatch){const p=state.profiles.find(x=>x.id===state.currentMatch.user_a||x.id===state.currentMatch.user_b)||{display_name:'your match'};openChat(state.currentMatch,p)}};

$('#submitReport').onclick=async()=>{const p=state.currentProfile;if(!p)return;try{if(backendReady){await sb('/rest/v1/reports',{method:'POST',body:{reporter_id:state.user.id,reported_id:p.id,reason:$('#reportReason').value,details:$('#reportDetails').value.trim()}});await sb('/rest/v1/blocks',{method:'POST',body:{blocker_id:state.user.id,blocked_id:p.id}})}closeModal('reportModal');closeModal('chatModal');toast('Report submitted and profile blocked');loadDiscover()}catch(e){toast(e.message)}};

async function renderMyProfile(){await loadOwnProfile();const p=state.profile,host=$('#myProfileCard');if(!p){host.innerHTML='<div class="card">No profile yet.</div>';return}const img=await mediaUrl(p.avatar_path);host.innerHTML=`<div class="card profileCard"><div class="photo">${img?`<img src="${esc(img)}">`:`<div class="initials">${initials(p.display_name)}</div>`}<div class="photoOverlay"><div class="name">${esc(p.display_name)}, ${age(p.birthdate)}</div><div class="meta">${esc(p.occupation||'')} · ${esc(p.city||'')}</div></div></div><div style="padding:16px"><div class="chips"><span class="pill good">Live capture ✓</span>${p.presence_submitted_at?'<span class="pill good">Presence submitted ✓</span>':''}${p.verification_status==='verified'?'<span class="pill good">Identity verified ✓</span>':'<span class="pill warn">Identity not verified</span>'}</div><p>${esc(p.bio||'')}</p></div></div>`}
$('#copyPassport').onclick=async()=>{const p=state.profile;if(!p)return;const text=`${p.display_name}, ${age(p.birthdate)}\n${p.city}${p.occupation?' · '+p.occupation:''}\nLooking for: ${p.relationship_intent}\n\n${p.bio}\n\n${(p.prompts||[]).map(x=>x.q+'\n'+x.a).join('\n\n')}\n\nInterests: ${(p.interests||[]).join(', ')}`;await navigator.clipboard.writeText(text);toast('Profile Passport copied')};
$('#pauseProfile').onclick=async()=>{if(!state.profile)return;const next=state.profile.profile_status==='paused'?'active':'paused';try{if(backendReady)await sb('/rest/v1/profiles?id=eq.'+state.user.id,{method:'PATCH',body:{profile_status:next}});state.profile.profile_status=next;if(!backendReady)localStorage.setItem('veramor_profile',JSON.stringify(state.profile));$('#pauseProfile').textContent=next==='paused'?'Resume profile':'Pause profile';toast(next==='paused'?'Profile paused':'Profile active')}catch(e){toast(e.message)}};
$('#exportData').onclick=async()=>{const data={account:{id:state.user?.id,email:state.user?.email},profile:state.profile,matches:await fetchMatches().catch(()=>[]),exported_at:new Date().toISOString()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='veramor-my-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)};
$('#deleteAccount').onclick=async()=>{if(!confirm('Permanently delete your VERAMOR account and associated app data?'))return;try{if(backendReady)await sb('/rest/v1/rpc/delete_my_account',{method:'POST',body:{}});localStorage.removeItem('veramor_session');localStorage.removeItem('veramor_profile');localStorage.removeItem('veramor_preview_user');state.session=state.user=state.profile=null;toast('Account deleted');show('welcome')}catch(e){toast(e.message)}};

(async()=>{if(backendReady){await refreshSession();if(state.user){if(state.profile?.profile_status==='active'||state.profile?.profile_status==='paused')show('discover');else show('onboarding')}}else{const u=JSON.parse(localStorage.getItem('veramor_preview_user')||'null');if(u){state.user=u;state.session={access_token:'preview'};await loadOwnProfile();if(state.profile)show('discover')}}})();
